repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint .
        language: system
        always_run: true
        pass_filenames: false
      - id: autopep8
        name: autopep8
        entry: poetry run autopep8 --in-place --recursive --verbose .
        language: system
        always_run: true
        pass_filenames: false
